apiVersion: signadot.com/v1
kind: SignadotResourcePlugin
metadata:
  name: sd-mariadb
spec:
  description: |
    Provision a MariaDB instance for one of HotROD's services.

    Sandbox should provide input 'dbname' for the name of the database.

    Plugin provisioner provides outputs 'host', 'port', 'root_password' for 
    an empty database instance tied to the lifetime of the sandbox.
  type: ExecPod
  execPod:
    template:
      metadata:
        namespace: {{ .Release.Namespace | quote }} 
      spec:
        serviceAccountName: {{ .Values.serviceAccountName | quote }}
        containers:
        - image: {{ .Values.Image | quote }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          name: plugin
          env:
          - name: NAMESPACE
            value: {{ .Release.Namespace | quote }}
 
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ .Values.serviceAccountName | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: sd-mariadb
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps", "secrets", "services"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: sd-mariadb
subjects:
- kind: ServiceAccount
  namespace: {{ .Release.Namespace | quote }}
  name: {{ .Values.serviceAccountName | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sd-mariadb
