name: terraform-amazon-s3
spec:
  description: |
    Provision and populates a temporary Amazon S3 bucket for use within a sandbox.

    Each sandbox resource request must specify a 'region' parameter,
    indicating the AWS region in which to provision the bucket (e.g. us-east-1).

    The temporary bucket name will be available as the output key 'provision.bucket-name'.

  runner:
    image: hashicorp/terraform
    basePodTemplate: @{include: ./plugin/pod-template.yaml}

  create:
  - name: provision
    inputs:
    - name: region
      valueFromSandbox: true

    outputs:
    - name: bucket-name
      from: /tmp/bucket-name

    env:
    - name: AWS_REGION
      valueFromInput: region

    script: @{include: ./plugin/provision.sh}

  delete:
  - name: deprovision
    inputs:
    - name: region
      valueFromSandbox: true
    - name: bucket-name
      valueFromStep:
        name: provision
        value: bucket-name

    env:
    - name: AWS_REGION
      valueFromInput: region
    - name: BUCKET_NAME
      valueFromInput: bucket-name

    script: @{include: ./plugin/deprovision.sh}