#!/usr/bin/env bash

set -euo pipefail

INPUT_DIR="${INPUT_DIR:-/signadot/plugin/input}"
OUTPUT_DIR="${OUTPUT_DIR:-/signadot/plugin/output}"

if [ $# -ne 2 ]; then
  echo "usage: deprovision <sandbox-id> <resource-name>"
  exit 1
fi

# Get values passed to us by Signadot Operator.
# These tell us which resource name in which Sandbox we should provision.
SANDBOX_ID=$1
RESOURCE_NAME=$2

echo "sandbox id: ${SANDBOX_ID}"
echo "resource name: ${RESOURCE_NAME}"

# Get values passed to us as "params" in the Sandbox's "resources" section.
REGION=$(cat "${INPUT_DIR}/region")

# Get the bucket name that we saved during 'provision'.
BUCKET_NAME=$(cat "${OUTPUT_DIR}/bucket-name")

# Delete the bucket.  --force allows to delete buckets containing objects.
# certain restrictions apply: some buckets may not be deleted, please see
# the AWS documentation for deleting buckets.
echo "Deleting bucket: ${BUCKET_NAME}"
aws --region "${REGION}" s3 rb "s3://${BUCKET_NAME}" --force
