name: amazon-sqs
spec:
  description: "@{embed: README.md}"

  runner:
    image: amazon/aws-cli
    namespace: signadot
    podTemplateOverlay: "@{embed: ./plugin/pod-template.yaml}"

  create:
  - name: provision
    inputs:
    - name: region
      valueFromSandbox: true
      as:
        env: AWS_REGION
    - name: attributes
      valueFromSandbox: true
      as:
        env: ATTRIBUTES
    - name: tags
      valueFromSandbox: true
      as:
        env: TAGS

    outputs:
    - name: queue-name
      valueFromPath: /tmp/queue-name
    - name: queue-url
      valueFromPath: /tmp/queue-url

    script: "@{embed: ./plugin/provision.sh}"

  delete:
  - name: deprovision
    inputs:
    - name: region
      valueFromSandbox: true
      as:
        env: AWS_REGION
    - name: queue-name
      valueFromStep:
        name: provision
        output: queue-name
      as:
        env: QUEUE_NAME
    - name: queue-url
      valueFromStep:
        name: provision
        output: queue-url
      as:
        env: QUEUE_URL

    script: "@{embed: ./plugin/deprovision.sh}"