#!/usr/bin/env bash

set -euo pipefail

INPUT_DIR="${INPUT_DIR:-/signadot/plugin/input}"
OUTPUT_DIR="${OUTPUT_DIR:-/signadot/plugin/output}"

if [ $# -ne 2 ]; then
  echo "usage: deprovision <sandbox-id> <resource-name>"
  exit 1
fi

# Get values passed to us by Signadot Operator.
# These tell us which resource name in which Sandbox we should provision.
SANDBOX_ID=$1
RESOURCE_NAME=$2

echo "sandbox id: ${SANDBOX_ID}"
echo "resource name: ${RESOURCE_NAME}"

export DBHOST=$(cat ${SECRET_DIR}/host) #"demo-test-1.cykseg9phlso.us-west-1.rds.amazonaws.com"
export DBUSER=$(cat ${SECRET_DIR}/user)
export DBPORT=$(cat ${SECRET_DIR}/post)
export PGPASSWORD=$(cat ${SECRET_DIR}/password)

DB_NAME=$(cat "${OUTPUT_DIR}/db-name")
psql --host=$DBHOST --username=$DBUSER --command="DROP DATABASE \"$DB_NAME\""
echo "Deleting db: ${DB_NAME}"
