name: mariadb
spec:
  description: "@{embed: README.md}"

  runner:
    image: dtzar/helm-kubectl
    namespace: signadot
    podTemplateOverlay: |
      spec:
        serviceAccountName: sd-mariadb

  create:
  - name: provision
    inputs:
    - name: dbname
      valueFromSandbox: true
      as:
        env: DBNAME

    outputs:
    - name: host
      valueFromPath: /tmp/host
    - name: port
      valueFromPath: /tmp/port
    - name: root-password
      valueFromPath: /tmp/root-password

    script: "@{embed: ./plugin/provision.sh}"

  delete:
    - name: deprovision
      script: "@{embed: ./plugin/deprovision.sh}"