name: mariadb
spec:
  description: |
    Provision a MariaDB instance

    Sandbox should provide input 'dbname' for the name of the database.
    Plugin provisioner provides outputs 'host', 'port', 'root-password' for 
    an empty database instance tied to the lifetime of the sandbox.

  runner:
    image: signadot/mariadb-plugin:v0.2.0
    namespace: signadot
    podTemplateOverlay: |
      spec:
        serviceAccountName: sd-mariadb
        containers:
        - name: plugin
          env:
          - name: NAMESPACE
            value: signadot

  create:
  - name: provision
    inputs:
    - name: dbname
      valueFromSandbox: true
      as:
        path: /signadot/plugin/input/dbname

    outputs:
    - name: host
      valueFromPath: /signadot/plugin/output/host
    - name: port
      valueFromPath: /signadot/plugin/output/port
    - name: root-password
      valueFromPath: /signadot/plugin/output/root_password

    script: |
      #!/bin/bash
      # exit when any command fails
      set -e

      mkdir -p /signadot/plugin/output
      /signadot/plugin/bin/provision ${SIGNADOT_SANDBOX_ID} ${SIGNADOT_RESOURCE_NAME}


  delete:
    - name: deprovision
      script: |
        #!/bin/bash
        # exit when any command fails
        set -e

        /signadot/plugin/bin/deprovision ${SIGNADOT_SANDBOX_ID} ${SIGNADOT_RESOURCE_NAME}