#!/usr/bin/env bash

set -euo pipefail

INPUT_DIR="${INPUT_DIR:-/signadot/provision/input}"
OUTPUT_DIR="${OUTPUT_DIR:-/signadot/provision/output}"

if [ $# -ne 2 ]; then
  echo "usage: deprovision <sandbox-id> <resource-name>"
  exit 1
fi

# Get values passed to us by Signadot Operator.
# These tell us which resource name in which Sandbox we should provision.
SANDBOX_ID=$1
RESOURCE_NAME=$2

echo "sandbox id: ${SANDBOX_ID}"
echo "resource name: ${RESOURCE_NAME}"

# Get values passed to us as "params" in the Sandbox's "resources" section.
REGION=$(cat "${INPUT_DIR}/region")

# Get the queue name and URL that we saved during 'provision'.
QUEUE_NAME=$(cat "${OUTPUT_DIR}/queue-name")
QUEUE_URL=$(cat "${OUTPUT_DIR}/queue-url")

# Delete the queue.
echo "Deleting queue: ${QUEUE_NAME}"
aws --region "${REGION}" sqs delete-queue --queue-url="${QUEUE_URL}"
